# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/information_sampling',
                'doc_host': 'https://hgzech.github.io',
                'git_url': 'https://github.com/hgzech/information_sampling',
                'lib_path': 'information_sampling'},
  'syms': {'information_sampling.core': {'information_sampling.core.foo': ('core.html#foo', 'information_sampling/core.py')}}}
